# Site settings
title: Prithvi Raj Narendra
description: 'BLE Savvy; Open-Source Enthusiast; Embedded Engineer;'
url: 'http://earthlord.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Prithvi Raj Narendra'
  email: p@earthlord.io
  twitter_username: prithvirajnaren
  facebook_username: prithvirajnarendra
  github_username:  EarthLord
  linkedin_username:  prithvirajnarendra
  cv: https://github.com/EarthLord/CV/raw/master/Prithvi_CV.pdf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

media:
  background: background.jpeg
#  profile: Logo3.png

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
